'use client';
import { Content } from 'next/font/google';

import React, { useState } from "react";
import { GoQuestion } from "react-icons/go";
import { IoIosArrowDown } from "react-icons/io";
import { IoIosArrowUp } from "react-icons/io";

const Aigirls =[
    {id:1,
    title:"Is this AI girl image generator really completely free?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"Yes! Our free AI girl image generator is 100% free with unlimited generations. You don't need to register, provide payment information, or worry about hidden costs. Our mission is to make AI girl image generation accessible to everyone through our free AI generator.",
    },

    {id:2,
    title:"Do I need to create an account to use the free AI girl image generator?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"No account or login is required for our free AI image generator. Simply visit our website, write your prompt, choose your preferred image size, and start generating AI girl images. We believe in making the AI image generation experience as frictionless as possible.",
    },

    {id:3,
    title:"How long does it take to generate an AI girl image?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"Most AI-generated images are created within 30 seconds using our free generator. However, during peak usage times when our AI image generation servers experience high demand, it may take slightly longer. Please be patient - quality AI girl image generation takes a bit of processing time.",
    },

    {id:4,
    title:"Are my AI-generated girl images saved on your server",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"No, we do not store any AI-generated images on our servers. This is by design to protect your privacy when using our free AI girl image generator. Once an AI image is generated, it's displayed to you and then it's gone from our system. Please download any AI-generated girl images you want to keep immediately.",
    },
    {id:5,
    title:"What image quality can i expect from the free AI girl image generator?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"Our free AI image generator offers multiple size options including square, landscape, and portrait formats. AI girl images are generated using advanced AI models to ensure high quality. The final quality also depends on how detailed your prompt is - more detailed prompts typically yield better AI-generated results.",
    },

     {id:6,
    title:"Can I use AI-generator girl images for commercial purposes?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"Yes, you can use AI girl images generated by our free generator for both personal and commercial projects. However, please be aware that AI-generated images may have certain legal considerations depending on your jurisdiction. We recommend reviewing your local regulations regarding AI-generated content for commercial use.",
    },
     {id:7,
    title:"Is there a limit to how many AI girl image  I can generate?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"No, there are absolutely no limits with our free AI girl image generator! You can generate as many AI images as you want, whenever you want. Experiment freely with different prompts and styles in our free generator without worrying about quotas or restrictions.",
    },
    {id:8,
    title:"What should I do if AI image generation fails?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"If generation fails with our free AI girl image generator, please try again - sometimes server load can cause temporary issues. If you're getting unexpected AI-generated results, try refining your prompt to be more specific and detailed. Check our AI image generation prompt writing guide for tips on creating effective descriptions.",
    },

    {id:9,
    title:"What image sizes are available in the free AI girl image generator?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"Our free AI image generator offers several size options to suit different needs: square (1:1), landscape (16:9), portrait (9:16), and other standard dimensions. Choose the size that best fits your intended use case for your AI-generated girl images, whether it's for social media, wallpapers, or other purposes.",
    },
    {id:10,
    title:"Is my privacy protected when using the free AI girl image generator?",
    icon1:<IoIosArrowDown />,
    icon2:<IoIosArrowUp />,
    Content:"Absolutely. Our free AI image generator doesn't require any personal information, doesn't track your activity beyond basic analytics, and doesn't store your AI-generated girl images. Your prompt history is saved locally in your browser, not on our servers. We take your privacy seriously when you use our free AI generator.",
    },

];

const FreeAi_Girl = () => {
  const [openId, setOpenId] = useState<number | null>(null);

  const toggle = (id: number) => {
    setOpenId(openId === id ? null : id);
  };

  return (
    <div id="freeai_girls"
    className="w-full min-h-[800px] flex flex-col items-center px-4 sm:px-6 lg:px-8 bg-[#10182b] mb-12 pt-10">
      
      {/* Title */}
      <h1 className="mt-12 text-4xl w-full sm:max-w-[1000px] font-bold text-center flex items-center gap-3 text-white">
        <GoQuestion className="text-indigo-400" />
        Free AI Girl Image Generator - Frequently Asked Questions
      </h1>

      <p className="text-center text-gray-400 mt-3 text-lg max-w-[690px]">
        Find answers to common questions about our free AI girl image generator - learn how to create stunning AI-generated images
      </p>

      {/* FAQ Accordion */}
      <div className="w-full max-w-[1200px] mx-auto mt-10 px-4 ">
  {Aigirls.map((item) => (
    <div
      key={item.id}
      className="mb-4 cursor-pointer"
      onClick={() => toggle(item.id)}
    >
      {/* Main box */}
      <div className="bg-[#1e293b] border-2 border-[#2c3543] hover:border-[#818cf8] rounded-lg px-4 py-8">
        
        {/* Question row */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            
            {/* ID circle */}
            <div className="w-10 h-10 flex items-center justify-center 
                            rounded-full bg-[#28334e] text-[#3c67ed] font-semibold">
              {item.id}
            </div>

            <h2 className="text-[#ebebeb] font-medium text-[25px]">
              {item.title}
            </h2>
          </div>

          {/* Icon on right */}
          <span className="text-indigo-400 text-2xl">
            {openId === item.id ? item.icon2 : item.icon1}
          </span>
        </div>

        {/* Answer INSIDE same div */}
        {openId === item.id && (
          <p className="text-gray-400 mt-4 text-sm leading-relaxed">
            {item.Content}
          </p>
        )}
      </div>
    </div>
  ))}
</div>
<div
  className="
    pt-10 mt-8
    w-full sm:w-[90%] md:w-[95%] lg:w-[60%]
    h-auto
    text-[#989ba8] text-center
    bg-[#22203a]
    rounded-2xl
    px-4 sm:px-8 py-6
    mx-auto
  "
>
  Still have questions about our free AI image generator?
  Feel free to contact us through our support channels.
</div>


    </div>
  );
};

export default FreeAi_Girl